### ISSUE TITLE
Rendering error during configuration of a new database view

### ISSUE THREAD

**Issue by MisterKCloud** [nocobase/nocobase#2684]
## Describe the bug

By adding a database view via the Collection Manager in Nocobase, the user has also to specify the fields. 
If the database view contains a field of type 'json' the UI immediately crashes when selecting 'JSON' as 'Field Interface'. 

## Version

Nocobase: Version 0.13.0-alpha.7
MySQL: 8.1.0 

## How To Reproduce

Preparation:

- Create a database view which consists of two columns named 'ID' (type = int) and 'Payload' (type = json)

1. Go to 'Collection Manager'
2. Click on '+ Create collection'
3. Scroll down to 'Connection to database view'
4. Enter a name and select the database view you would like to connection
5. Go to 'Fields' configuration and select for the field of type 'json' the field interface 'Advanced: JSON'
6. Error message should appear

## Expected behavior

No error message and the possibility to save. 

## Screenshots

<img width="656" alt="Screenshot 2023-09-20 at 09 14 48" src="https://github.com/nocobase/nocobase/assets/136599393/0ba601b7-b4ea-4589-8678-b2c3136e0234">
<img width="916" alt="Screenshot 2023-09-20 at 09 14 14" src="https://github.com/nocobase/nocobase/assets/136599393/df7b02de-f92f-408d-9636-cd9c10517119">

## Desktop (please complete the following information)

- Browser [e.g. chrome v102, safari]

## Additional context

No further details.

**Comment by katherinehhh** [comment]
Thank you for your feedback! The issue has been resolved

**Comment by MisterKCloud** [comment]
Dear @katherinehhh I just tested it with Version 0.16.0-alpha.3.20231120114347 but a similar issue still occurs. Although there is no error message anymore, I will be redirected to a "white screen" and cannot recover the configuration.

Any ideas?
