### ISSUE TITLE
From v1.5.13 file upload is broken with S3 driver

### ISSUE THREAD

**Issue by Lelenaic** [nocobase/nocobase#6279]
## * Describe the bug

When I select a file to upload from [v1.5.13](https://github.com/nocobase/nocobase/releases/tag/v1.5.13) nothing appears to be uploaded. I downgraded to [v1.5.12](https://github.com/nocobase/nocobase/releases/tag/v1.5.12) and it works. So according to the changelog, I guess this is https://github.com/nocobase/nocobase/pull/6260 which breaks the upload. It appears to be only with S3 for the moment. I tried with local storage and it works.

## * Environment

- NocoBase version: v1.5.12/13

- Database type and version: PG 16
  

- OS: MacOS

- Deployment Methods: Docker

- Docker image version: 1.5.12/13

## * How To Reproduce

Configure nocobase with S3 file storage driver and then upload a file in any form.

## Expected behavior

The file should be uploaded and shown in the form files section.

## Screenshots

![Image](https://github.com/user-attachments/assets/6ce92595-8f99-4b3b-8f08-29db1b738562)

## Logs

No error in the logs, there's just a XHR request with a 200 on file upload (the file is correctly uploaded to the S3 bucket).

**Comment by zhouyanliang** [comment]
This Issue was fixed in 1.5.16.

**Comment by josucafd** [comment]
Here is the bug still present.

NocoBase version: 1.5.16

Observed behavior:

The file is saved in the S3/MinIO Bucket correctly (confirmed via MinIO console). In the NocoBase interface, the file is not displayed in the listing, as if the upload did not occur.

![Image](https://github.com/user-attachments/assets/bc454897-7294-40e0-8e4b-6c5371d4cd70)

**Comment by mytharcher** [comment]
Could you show us your storage configuration? Seems `path` caused this.

**Comment by josucafd** [comment]
> Você poderia nos mostrar sua configuração de armazenamento? Parece ter causado isso.`path`

This is the configuration I'm using

![Image](https://github.com/user-attachments/assets/1a44b674-a20e-4ace-a73a-b69b0900b4f0)

**Comment by mytharcher** [comment]
You may need to change "Access base URL" to `http://<your ip>:9004/pilotos`. Because the "Endpoint" you configured as IP format, this makes the URL to be force path style. So you need to add the bucket name to base URL.

We will add more document and examples to our doc site later, in case others have the same confusion.

**Comment by josucafd** [comment]
@mytharcher Perfect, it worked here, thank you very much

**Comment by Lelenaic** [comment]
> This Issue was fixed in 1.5.16.

Thanks, the issue is indeed fixed in 1.5.16.
