### ISSUE TITLE
UI Editor unusable under firefox

### ISSUE THREAD

**Issue by Sphereso** [nocobase/nocobase#7837]
## * Describe the bug

UI Editor overlays are completely misaligned or sized wrong under firefox 
<img width="1233" height="373" alt="Image" src="https://github.com/user-attachments/assets/47a8dd6e-fb67-4eee-bf4b-6715b1e7be94" />

I think this mostly occours through the use of
`position: relative` + `display: inline`
on the container of the overlay and how firefox handles this incorrectly
https://bugzilla.mozilla.org/show_bug.cgi?id=489100

## * Environment

- NocoBase version: v2.0.0-alpha.37

## * How To Reproduce

Open UI-Editor under firefox browser

## Expected behavior
In Chromium:
<img width="1301" height="373" alt="Image" src="https://github.com/user-attachments/assets/4e8a0b9c-3827-4c61-be20-915b17e51469" />

**Comment by nielsq** [comment]
+1

**Comment by hongboji** [comment]
Please use the latest versions of Firefox and NocoBase to check if the problem exists.

**Comment by nairsajeesh** [comment]
I am facing the same issue. UI Editor doesn't work properly on Firefox and FF based browsers (including Zen browser). You need to hover on the hamburger icon a couple of times before the menu opens. Also sometimes the layout on some of the forms appear scattered. 

This issue is happening on all the NCl versions above 1.9.10 onwards. Same goes for alpha version as well. 

However, everything works on chromium based browsers.

I'm using Fedora 43 Gnome.

**Comment by saraTabbane** [comment]
Hi, I tried to reproduce this issue on Windows using Docker, but was not able to reproduce the problem.

**Environment:**

NocoBase versions: v1.9.47 and latest
OS: Windows 11
Setup: Docker Desktop (local) with PostgreSQL
Browsers: Firefox (latest) and Chrome (latest)

**Steps:**

1. Opened pages with nested grid blocks
2. Checked orange overlay borders in UI editor mode
3. Compared toolbar positioning between Firefox and Chrome

**Result:**

Overlay borders display correctly in both browsers
Toolbar positioning is consistent
No misalignment observed on nested grid blocks

So the issue does not appear in this environment.

**Comment by nairsajeesh** [comment]
This has been resolved after an update in early Feb. I can't tell which version did it, but as of today it seem fixed.

**Comment by saraTabbane** [comment]
So,this issue may be ready to close unless someone can still reproduce it on a supported version.
